spring :
  servlet:
     multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul
  redis:
    host: redis-service
    port: 6379
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    ssl:
      enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/stomachforce?serverTimezone=Asia/Seoul
    username: admin
    password: ${DB_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

#logging:
#  level:
#    root: info
#  file:
#    name: logs/app.log

jwt:
  expiration: 30
  secretKey: ${JWT_SECRET}
  expirationRT: 288000
  secretKeyRT: ${JWT_SECRET_RT}

oauth:
  google:
    client-id: ${OUATH_CLIENT}
    client-secret: ${OUATH_SECRET}
    redirect_uri: ${OUATH_REDIRECT}

cloud:
  aws:
    credentials:
      access-key: ${AWS_KEY}
      secret-key: ${AWS_SECRET}
    region:
      static: ap-northeast-2
    s3:
      bucket: stomachforce
