spring :
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/stomachforce?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

#logging:
#  level:
#    root: info
#  file:
#    name: logs/app.log

jwt:
  expiration: 30
  #  beyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkey
  secretKey: YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2VrbnNlY3JldGtleWJleW9uZGFjY2Vzc3RvZWtuc2VjcmV0a2V5YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXk=
  expirationRT: 288000
  #  beyondrefreshsecrettokenkeybeyondrefreshsecrettokenkeybeyondrefreshsecrettokenkey
  secretKeyRT: YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5

oauth:
  google:
    client-id: 752078374240-4tdtnn7i8de5jpavh9qbupu7nbimt5rn.apps.googleusercontent.com
    client-secret: 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
    redirect_uri: http://localhost:3000/oauth/google/redirect

cloud:
  aws:
    credentials:
      access-key: AKIAT4GVRVENWLN7QFBJ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: stomachforce
